config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'projects/fancytree_recents', to: 'projects#fancytree_recents', defaults: { format: 'json' }
    get 'projects/:status', to: 'projects#fancytree', defaults: { format: 'json' }
    get 'tasks', to: 'tasks#index', defaults: { format: 'json' }
    post 'tasks', to: 'tasks#create'
    patch 'tasks/:id', to: 'tasks#update', as: nil
    put 'tasks/:id', to: 'tasks#update', as: nil
    delete 'tasks/:id', to: 'tasks#destroy', as: nil
  end

  resources :profiles
  resources :subprojects
  resources :projects
  resources :phases
  resources :clients
  resources :notify_messages

  scope 'reports' do
    get '/', to: 'reports#index', as: :reports
    get '/clients', to: 'reports#clients', as: :reports_clients
    get '/projects', to: 'reports#projects', as: :reports_projects
    get '/subprojects', to: 'reports#subprojects', as: :reports_subprojects
    get '/users', to: 'reports#users', as: :reports_users
    get '/projects_users', to: 'reports#projects_users', as: :reports_projects_users
  end

  devise_for :users, skip: [:registrations], controllers: {
    sessions:  'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/login' => 'users/sessions#new', :as => 'login'
    get '/logout' => 'users/sessions#destroy', :as => 'logout'
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(name: :asc)
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to edit_profile_path(@user), notice: t('flash_messages.users.created') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to edit_profile_path(@user), notice: t('flash_messages.users.updated') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: t('flash_messages.users.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation,
                                 :notify_missing_tasks, :slackuser, :admin, :status)
  end
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@user, url: @user.new_record? ? profiles_path : profile_path(@user)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.input :status %>
    <%= f.input :slackuser %>
    <%= f.input :notify_missing_tasks, as: :boolean %>
    <%= f.input :admin, as: :boolean %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to t('back'), profiles_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1><%= t('users.edit') %></h1>

<%= render 'form', user: @user %>

app/views/profiles/index.html.erb
<h1><%= t('users.list') %></h1>

<p>
  <%= link_to t('users.new'), new_profile_path, class: 'btn btn-primary' %>
</p>

<table class="table table-striped table-bordered table-valign-center">
  <thead>
  <tr>
    <th><%= t('name') %></th>
    <th><%= t('email') %></th>
    <th><%= t('is_admin') %></th>
    <th><%= t('notification_enabled') %></th>
    <th><%= t('slack_user') %></th>
    <th><%= t('status') %></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.admin? %></td>
      <td><%= user.notify_missing_tasks? %></td>
      <td><%= user.slackuser %></td>
      <td><%= user.status %></td>
      <td>
        <%= link_to t('edit'), edit_profile_path(user), class: 'btn btn-info btn-sm' %>
        <%= link_to t('delete'), profile_path(user), method: :delete, data: { confirm: t('msg_confirm') },
                    class: 'btn btn-danger btn-sm' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/profiles/new.html.erb
<h1><%= t('users.new') %></h1>

<%= render 'form', user: @user %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @phase.name %>
</p>

<%= link_to t('edit'), edit_phase_path(@phase) %> |
<%= link_to 'Back', phases_path %>