config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'projects/fancytree_recents', to: 'projects#fancytree_recents', defaults: { format: 'json' }
    get 'projects/:status', to: 'projects#fancytree', defaults: { format: 'json' }
    get 'tasks', to: 'tasks#index', defaults: { format: 'json' }
    post 'tasks', to: 'tasks#create'
    patch 'tasks/:id', to: 'tasks#update', as: nil
    put 'tasks/:id', to: 'tasks#update', as: nil
    delete 'tasks/:id', to: 'tasks#destroy', as: nil
  end

  resources :profiles
  resources :subprojects
  resources :projects
  resources :phases
  resources :clients
  resources :notify_messages

  scope 'reports' do
    get '/', to: 'reports#index', as: :reports
    get '/clients', to: 'reports#clients', as: :reports_clients
    get '/projects', to: 'reports#projects', as: :reports_projects
    get '/subprojects', to: 'reports#subprojects', as: :reports_subprojects
    get '/users', to: 'reports#users', as: :reports_users
    get '/projects_users', to: 'reports#projects_users', as: :reports_projects_users
  end

  devise_for :users, skip: [:registrations], controllers: {
    sessions:  'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/login' => 'users/sessions#new', :as => 'login'
    get '/logout' => 'users/sessions#destroy', :as => 'logout'
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_form_data

  def index
    @group_by = ['subproject_phases.id', 'users.id']
    @order_by = ['projects.name asc', 'subprojects.name asc', 'phases.name asc', 'users.name asc']
    @select   = ['projects.name', 'subprojects.name', 'phases.name', 'users.name', 'sum(time)']

    get_results
  end

  def clients
    @group_by = ['clients.id']
    @order_by = ['clients.name asc']
    @select   = ['clients.name', 'sum(time)']

    get_results
  end

  def projects
    @group_by = ['projects.id']
    @order_by = ['projects.name asc']
    @select   = ['projects.name', 'sum(time)']

    get_results
  end

  def subprojects
    @group_by = ['subprojects.id']
    @order_by = ['projects.name asc', 'subprojects.name asc']
    @select   = ['projects.name', 'subprojects.name', 'sum(time)']

    get_results
  end

  def users
    @group_by = ['users.id']
    @order_by = ['users.name asc']
    @select   = ['users.name', 'sum(time)']

    get_results
  end

  def projects_users
    @group_by = ['projects.id', 'users.id', 'year(started_at)', 'month(started_at)']
    @order_by = ['year(started_at) asc', 'month(started_at) asc', 'users.name asc', 'projects.name asc']
    @select   = ['projects.name', 'users.name', 'sum(time)', 'year(started_at)', 'month(started_at)', 'started_at']

    @results = Task.includes(:user, subproject_phase: [:phase, subproject: [project: [:client]]])
                   .group(@group_by)
                   .order(@order_by)

    @results = @results.where('year(tasks.started_at) = ?', params[:year]) if params[:year].present?
    @results = @results.where('month(tasks.started_at) = ?', params[:month]) if params[:month].present?
    @results = @results.where('users.id = ?', params[:user]) if params[:user].present?

    @results = @results.pluck(@select.join(', '))

    @report = Hash.new do |hash, key|
      users = Hash.new do |user, user_key|
        user[user_key] = []
      end
      hash[key] = users
    end

    @results.each do |result|
      year = result[3]
      month = result[4].to_s.rjust(2, '0')
      user = result[1]

      @report["#{year}-#{month}-01"][user].push(
        name: result[0],
        time: result[2]
      )
    end
  end

  private

  def get_results
    if params[:group_month].present?
      @select   += ['year(started_at)', 'month(started_at)']
      @group_by += ['year(started_at)', 'month(started_at)']
      @order_by += ['started_at asc']
    end

    @results = Task.includes(:user, subproject_phase: [:phase, subproject: [project: [:client]]])
                   .group(@group_by)
                   .order(@order_by)

    @results = @results.where('year(tasks.started_at) = ?', params[:year]) if params[:year].present?
    @results = @results.where('month(tasks.started_at) = ?', params[:month]) if params[:month].present?
    @results = @results.where('day(tasks.started_at) = ?', params[:day]) if params[:day].present?
    @results = @results.where('projects.id = ?', params[:project]) if params[:project].present?
    @results = @results.where('subprojects.id = ?', params[:subproject]) if params[:subproject].present?
    @results = @results.where('users.id = ?', params[:user]) if params[:user].present?

    @results = @results.pluck(@select.join(', '))
  end

  def set_form_data
    @years    = Task.pluck('distinct(year(started_at))')
    @months   = (1..12).map { |m| [I18n.l(DateTime.parse(Date::MONTHNAMES[m]), format: '%B'), m] }
    @days     = (1..31).map { |m| [m] }
    @users    = User.order('name asc').map { |u| [u.name, u.id] }
    @projects = Project.order('name asc').map { |p| [p.name, p.id] }

    @subprojects = if params[:project].present?
                     Subproject.order('name asc').where('project_id = ?', params[:project]).map { |p| [p.name, p.id] }
                   else
                     []
                   end
  end
end

app/views/reports/_header.html.erb
<ul class="nav nav-tabs">
  <li class="<%= action_name == 'index' ? 'active' : '' %>">
    <%= link_to t('.nav_general'), reports_path(request.query_parameters) %>
  </li>
  <li class="<%= action_name == 'clients' ? 'active' : '' %>">
    <%= link_to t('.nav_clients'), reports_clients_path(request.query_parameters) %>
  </li>
  <li class="<%= action_name == 'projects' ? 'active' : '' %>">
    <%= link_to t('.nav_projects'), reports_projects_path(request.query_parameters) %>
  </li>
  <li class="<%= action_name == 'subprojects' ? 'active' : '' %>">
    <%= link_to t('.nav_subprojects'), reports_subprojects_path(request.query_parameters) %>
  </li>
  <li class="<%= action_name == 'users' ? 'active' : '' %>">
    <%= link_to t('.nav_users'), reports_users_path(request.query_parameters) %>
  </li>
  <li class="<%= action_name == 'projects_users' ? 'active' : '' %>">
    <%= link_to t('.nav_projects_users'), reports_projects_users_path(request.query_parameters) %>
  </li>
</ul>

<hr>

<form action="" class="form-inline">
  <div class="form-group form-group--gutter">
    <%= label_tag :year, t('year') %>
    <%= select_tag :year, options_for_select([''] + @years, params[:year]), class: 'form-control ' %>
  </div>

  <div class="form-group form-group--gutter">
    <%= label_tag :month, t('month') %>
    <%= select_tag :month, options_for_select([''] + @months, params[:month]), class: 'form-control' %>
  </div>

  <% if action_name != 'projects_users' %>

      <div class="form-group form-group--gutter">
        <%= label_tag :day, t('day') %>
        <%= select_tag :day, options_for_select([''] + @days, params[:day]), class: 'form-control' %>
      </div>

      <div class="form-group form-group--gutter">
        <%= label_tag :group_month, t('.group_month') %>
        <%= check_box_tag :group_month, true, params[:group_month] %>
      </div>

      <div class="form-group form-group--gutter">
        <%= label_tag :project, t('app.project') %>
        <%= select_tag :project, options_for_select([''] + @projects, params[:project]), class: 'form-control select2' %>
      </div>

      <div class="form-group form-group--gutter">
        <%= label_tag :subproject, t('app.subproject') %>
        <%= select_tag :subproject, options_for_select([''] + @subprojects, params[:subproject]), class: 'form-control select2' %>
      </div>

  <% end %>

  <div class="form-group form-group--gutter">
    <%= label_tag :user, t('app.user') %>
    <%= select_tag :user, options_for_select([''] + @users, params[:user]), class: 'form-control' %>
  </div>

  <div class="form-group form-group--gutter">
    <%= button_tag t('filter'), class: 'btn btn-primary' %>
  </div>

</form>

<hr>

app/views/reports/clients.html.erb
<%= render 'header' %>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <% if params[:group_month] %>
      <th><%= t('year') %></th>
      <th><%= t('month') %></th>
    <% end %>
    <th><%= t('app.client') %></th>
    <th><%= t('hours_spent') %></th>
  </tr>
  </thead>
  <% total = 0 %>
  <% if @results.size > 0 %>
    <tbody>
    <% @results.each do |result| %>
      <% total += result[1] %>
      <tr>
        <% if params[:group_month] %>
          <td><%= result[2] %></td>
          <td><%= result[3] %></td>
        <% end %>
        <td><%= result[0] %></td>
        <td><%= number_with_precision(result[1].to_f / 3600, precision: 2, delimiter: '') %></td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <th colspan="<%= @results.first.size - 1 %>"></th>
      <th><%= number_with_precision(total.to_f / 3600, precision: 2, delimiter: '') %></th>
    </tr>
    </tfoot>
  <% end %>
</table>

app/views/reports/index.html.erb
<%= render 'header' %>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <% if params[:group_month] %>
      <th><%= t('year') %></th>
      <th><%= t('month') %></th>
    <% end %>
    <th><%= t('app.project') %></th>
    <th><%= t('app.subproject') %></th>
    <th><%= t('app.phase') %></th>
    <th><%= t('app.user') %></th>
    <th><%= t('hours_spent') %></th>
  </tr>
  </thead>
  <% total = 0 %>
  <% if @results.size > 0 %>
    <tbody>
    <% @results.each do |result| %>
      <% total += result[4] %>
      <tr>
        <% if params[:group_month] %>
          <td><%= result[5] %></td>
          <td><%= result[6] %></td>
        <% end %>
        <td><%= result[0] %></td>
        <td><%= result[1] %></td>
        <td><%= result[2] %></td>
        <td><%= result[3] %></td>
        <td><%= number_with_precision(result[4].to_f / 3600, precision: 2, delimiter: '') %></td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <th colspan="<%= @results.first.size - 1 %>"></th>
      <th><%= number_with_precision(total.to_f / 3600, precision: 2, delimiter: '') %></th>
    </tr>
    </tfoot>
  <% end %>
</table>

app/views/reports/projects.html.erb
<%= render 'header' %>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <% if params[:group_month] %>
        <th><%= t('year') %></th>
        <th><%= t('month') %></th>
    <% end %>
    <th><%= t('app.project') %></th>
    <th><%= t('hours_spent') %></th>
  </tr>
  </thead>
  <% total = 0 %>
  <% if @results.size > 0 %>
      <tbody>
      <% @results.each do |result| %>
          <% total += result[1] %>
          <tr>
            <% if params[:group_month] %>
                <td><%= result[2] %></td>
                <td><%= result[3] %></td>
            <% end %>
            <td><%= result[0] %></td>
            <td><%= number_with_precision(result[1].to_f / 3600, precision: 2, delimiter: '') %></td>
          </tr>
      <% end %>
      </tbody>
      <tfoot>
      <tr>
        <th colspan="<%= @results.first.size - 1 %>"></th>
        <th><%= number_with_precision(total.to_f / 3600, precision: 2, delimiter: '') %></th>
      </tr>
      </tfoot>
  <% end %>
</table>

app/views/reports/projects_users.html.erb
<%= render 'header' %>

<table class="table table-hover">
  <% @report.each do |date, users| %>
    <tr class="success">
      <td>
        <strong>
          <%= l(date.to_date, format: '%B') %>
        </strong>
      </td>
      <td>
        <strong>
          <%= l(date.to_date, format: '%Y') %>
        </strong>
      </td>
    </tr>

    <% users.each do |user, projects| %>
      <tr class="info">
        <td colspan="2">
          <%= user %>
        </td>
      </tr>
      <% projects.each do |project| %>
        <tr>
          <td><%= project[:name] %></td>
          <td><%= number_with_precision(project[:time].to_f / 3600, precision: 2, delimiter: '') %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
</table>

app/views/reports/subprojects.html.erb
<%= render 'header' %>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <% if params[:group_month] %>
      <th><%= t('year') %></th>
      <th><%= t('month') %></th>
    <% end %>
    <th><%= t('app.project') %></th>
    <th><%= t('app.subproject') %></th>
    <th><%= t('hours_spent') %></th>
  </tr>
  </thead>
  <% total = 0 %>
  <% if @results.size > 0 %>
    <tbody>
    <% @results.each do |result| %>
      <% total += result[2] %>
      <tr>
        <% if params[:group_month] %>
          <td><%= result[3] %></td>
          <td><%= result[4] %></td>
        <% end %>
        <td><%= result[0] %></td>
        <td><%= result[1] %></td>
        <td><%= number_with_precision(result[2].to_f / 3600, precision: 2, delimiter: '') %></td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <th colspan="<%= @results.first.size - 1 %>"></th>
      <th><%= number_with_precision(total.to_f / 3600, precision: 2, delimiter: '') %></th>
    </tr>
    </tfoot>
  <% end %>
</table>

app/views/reports/users.html.erb
<%= render 'header' %>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <% if params[:group_month] %>
      <th><%= t('year') %></th>
      <th><%= t('month') %></th>
    <% end %>
    <th><%= t('app.user') %></th>
    <th><%= t('hours_spent') %></th>
  </tr>
  </thead>
  <% total = 0 %>
  <% if @results.size > 0 %>
    <tbody>
    <% @results.each do |result| %>
      <% total += result[1] %>
      <tr>
        <% if params[:group_month] %>
          <td><%= result[2] %></td>
          <td><%= result[3] %></td>
        <% end %>
        <td><%= result[0] %></td>
        <td><%= number_with_precision(result[1].to_f / 3600, precision: 2, delimiter: '') %></td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <th colspan="<%= @results.first.size - 1 %>"></th>
      <th><%= number_with_precision(total.to_f / 3600, precision: 2, delimiter: '') %></th>
    </tr>
    </tfoot>
  <% end %>
</table>