config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'projects/fancytree_recents', to: 'projects#fancytree_recents', defaults: { format: 'json' }
    get 'projects/:status', to: 'projects#fancytree', defaults: { format: 'json' }
    get 'tasks', to: 'tasks#index', defaults: { format: 'json' }
    post 'tasks', to: 'tasks#create'
    patch 'tasks/:id', to: 'tasks#update', as: nil
    put 'tasks/:id', to: 'tasks#update', as: nil
    delete 'tasks/:id', to: 'tasks#destroy', as: nil
  end

  resources :profiles
  resources :subprojects
  resources :projects
  resources :phases
  resources :clients
  resources :notify_messages

  scope 'reports' do
    get '/', to: 'reports#index', as: :reports
    get '/clients', to: 'reports#clients', as: :reports_clients
    get '/projects', to: 'reports#projects', as: :reports_projects
    get '/subprojects', to: 'reports#subprojects', as: :reports_subprojects
    get '/users', to: 'reports#users', as: :reports_users
    get '/projects_users', to: 'reports#projects_users', as: :reports_projects_users
  end

  devise_for :users, skip: [:registrations], controllers: {
    sessions:  'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/login' => 'users/sessions#new', :as => 'login'
    get '/logout' => 'users/sessions#destroy', :as => 'logout'
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar Time Tracking</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>

  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#03c98a">
  <meta name="theme-color" content="#ffffff">
</head>

<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Calendar Time Tracking', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to t('profile'), edit_user_registration_path %>
          <% if current_user.admin? %>
            <li class="dropdown">
              <a href="#"
                 class="dropdown-toggle"
                 data-toggle="dropdown"
                 role="button"
                 aria-haspopup="true"
                 aria-expanded="false">
                <%= t('nav_view_as') %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <% users_list.each do |user| %>
                  <%= content_for :li, link_to(user.name, root_path(user: user.id)) %>
                <% end %>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#"
                 class="dropdown-toggle"
                 data-toggle="dropdown"
                 role="button"
                 aria-haspopup="true"
                 aria-expanded="false">
                <%= t('nav_admin') %>
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <%= content_tag :li, link_to(t('app.projects'), projects_path) %>
                <%= content_tag :li, link_to(t('app.phases'), phases_path) %>
                <%= content_tag :li, link_to(t('app.clients'), clients_path) %>
                <%= content_tag :li, link_to(t('app.users'), profiles_path) %>
                <%= content_tag :li, link_to(t('app.reports'), reports_path) %>
                <%= content_tag :li, link_to(t('app.messages'), notify_messages_path) %>
              </ul>
            </li>
          <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= content_tag :li, link_to(t('logout'), logout_path) %>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <%= content_tag :div, notice, class: 'alert alert-info', role: 'role' if notice.present? %>
  <%= content_tag :div, alert, class: 'alert alert-danger', role: 'role' if alert.present? %>
  <%= yield %>
</div>

<%= yield :before_javascript %>
<%= javascript_include_tag 'application' %>
<%= yield :javascript %>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar Time Tracking</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#03c98a">
  <meta name="theme-color" content="#ffffff">
</head>

<body>
<div class="container-fluid">
  <%= content_tag :div, notice, class: 'alert alert-info', role: 'role' if notice.present? %>
  <%= content_tag :div, alert, class: 'alert alert-danger', role: 'role' if alert.present? %>
  <%= yield %>
</div>

<%= yield :before_javascript %>
<%= javascript_include_tag 'application' %>
<%= yield :javascript %>

</body>
</html>