config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'projects/fancytree_recents', to: 'projects#fancytree_recents', defaults: { format: 'json' }
    get 'projects/:status', to: 'projects#fancytree', defaults: { format: 'json' }
    get 'tasks', to: 'tasks#index', defaults: { format: 'json' }
    post 'tasks', to: 'tasks#create'
    patch 'tasks/:id', to: 'tasks#update', as: nil
    put 'tasks/:id', to: 'tasks#update', as: nil
    delete 'tasks/:id', to: 'tasks#destroy', as: nil
  end

  resources :profiles
  resources :subprojects
  resources :projects
  resources :phases
  resources :clients
  resources :notify_messages

  scope 'reports' do
    get '/', to: 'reports#index', as: :reports
    get '/clients', to: 'reports#clients', as: :reports_clients
    get '/projects', to: 'reports#projects', as: :reports_projects
    get '/subprojects', to: 'reports#subprojects', as: :reports_subprojects
    get '/users', to: 'reports#users', as: :reports_users
    get '/projects_users', to: 'reports#projects_users', as: :reports_projects_users
  end

  devise_for :users, skip: [:registrations], controllers: {
    sessions:  'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/login' => 'users/sessions#new', :as => 'login'
    get '/logout' => 'users/sessions#destroy', :as => 'logout'
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'
end

app/models/notify_message.rb
class NotifyMessage < ApplicationRecord
  validates :message, presence: true
end

app/controllers/notify_messages_controller.rb
class NotifyMessagesController < ApplicationController
  before_action :set_notify_message, only: %i[show edit update destroy]

  def index
    @notify_messages = NotifyMessage.all
  end

  def show; end

  def new
    @notify_message = NotifyMessage.new
  end

  def edit; end

  def create
    @notify_message = NotifyMessage.new(notify_message_params)

    respond_to do |format|
      if @notify_message.save
        format.html { redirect_to notify_messages_url, notice: t('flash_messages.messages.created') }
        format.json { render :show, status: :created, location: @notify_message }
      else
        format.html { render :new }
        format.json { render json: @notify_message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @notify_message.update(notify_message_params)
        format.html { redirect_to notify_messages_url, notice: t('flash_messages.messages.updated') }
        format.json { render :show, status: :ok, location: @notify_message }
      else
        format.html { render :edit }
        format.json { render json: @notify_message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @notify_message.destroy
    respond_to do |format|
      format.html { redirect_to notify_messages_url, notice: t('flash_messages.messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def set_notify_message
    @notify_message = NotifyMessage.find(params[:id])
  end

  def notify_message_params
    params.require(:notify_message).permit(:message)
  end
end

app/views/notify_messages/_form.html.erb
<%= simple_form_for(@notify_message) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :message %>
    </div>

    <ul>
        <li>%%username%% | <%= t('notify_messages.replace_username') %></li>
        <li>%%date%% | <%= t('notify_messages.replace_date') %> </li>
    </ul>

    <br>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-primary' %>
      <%= link_to t('back'), notify_messages_path, class: 'btn btn-default' %>
    </div>
<% end %>


<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
<script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace( 'notify_message_message' );
</script>

app/views/notify_messages/edit.html.erb
<h1><%= t('messages.edit') %></h1>

<%= render 'form', client: @notify_message %>

app/views/notify_messages/index.html.erb
<h1><%= t('messages.list') %></h1>

<p>
  <%= link_to t('messages.new'), new_notify_message_path, class: 'btn btn-primary' %>
</p>

<table class="table table-striped table-bordered table-valign-center">
  <thead>
  <tr>
    <th><%= t('app.message') %></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @notify_messages.each do |notify_messages| %>
      <tr>
        <td class="notify_messages_content"><%= raw notify_messages.message %></td>
        <td>
          <%= link_to t('edit'), edit_notify_message_path(notify_messages), class: 'btn btn-info btn-sm' %>
          <%= link_to t('delete'), notify_messages, method: :delete, data: { confirm: t('msg_confirm') },
                      class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/notify_messages/new.html.erb
<h1><%= t('messages.new') %></h1>

<%= render 'form', client: @notify_message %>